version: '3.3'
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: 'secret1'
    ports:
      - '33060:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: